version: "3"
services:
  ocaml:
    build: .
    image: brainpower/ocaml-from-the-very-beginning-dev
    ports:
      - "8443:8443"
    volumes:
      - "./.git:/repo/.git"
      - "./chapters:/repo/chapters"
      - "./.gitignore:/repo/.gitignore"
      - "./dune-project:/repo/dune-project"
      - "./README.md:/repo/README.md"
    command: code-server --allow-http --no-auth /repo
