
version: 2
jobs:
  build:
    docker:
      - image: brainpower/ocaml-from-the-very-beginning-dev
    working_directory: /repo
    steps:
      - checkout:
          path: ~/checkout
      - run:
          name: Sync
          command: sudo cp -rf ~/checkout/* /repo/ && sudo chown -R opam:opam /repo
      - run:
          name: Test
          command: source ~/.profile && dune runtest