
version: 2
jobs:
  build:
    docker:
      - image: marionebl/ocaml-from-the-very-beginning-dev
    working_directory: /repo
    steps:
      - checkout:
          path: ~/checkout
      - run:
          name: Sync
          command: cp -rf ~/checkout/* /repo/
      - run:
          name: Test
          command: source ~/.profile && dune runtest